### ISSUE TITLE
很好

### ISSUE THREAD

**Issue by CGS1130299247** [wei18810109052/CWWeChat#2]
pod install之后

[!] The dependency `SnapKit (~> 0.15.0)` is not used in any concrete target. The dependency `MJRefresh` is not used in any concrete target. The dependency `SVProgressHUD (~> 1.1.3)` is not used in any concrete target.

**Comment by cwwise** [comment]
你下载的是master分支，还是Tag3.0的？我重新下载了一份，测试了没有问题。
你本地的cocoapod版本是多少？可以尝试把podfile.lock文件删除 再试试。。
看看可不可以解决。。
